[dlt]
url = "https://datachart.500.com/dlt/history/newinc/history.php"
name = "大乐透"
code = "dlt"
start = "07001"
end = "999999"


[ssq]
url = "https://datachart.500.com/ssq/history/newinc/history.php"
name = "双色球"
code = "ssq"
start = "03001"
end = "999999"

[kl8]
url = "https://www.lottery.gov.cn/historykj/history_1.jspx?_ltype=kl8"
name = "快乐8"
code = "kl8"
start = "2007-01-01"
end = "2017-01-01"

[qxc]
url = "https://www.lottery.gov.cn/historykj/history_1.jspx?_ltype=qxc"
name = "七星彩"
code = "qxc"
start = "2007-01-01"
end = "2017-01-01"
